---
- hosts: localhost
  gather_facts: yes
  #  vars:
  #  rpi_hostname: rpidus.redhat.com
  #vars_files:
  #  - /root/ansible-playbook-rpi_garage_door_opener-vars.yml
  become: yes
  tasks:
    - name: install packages
      package:
        name:
          - vim
          - libreoffice
        state: present

