---
- hosts: localhost
  gather_facts: yes
  #  vars:
  #  myhostame: fedora-on-rpi-workstation.local
  #vars_files:
  #  - /root/vars.yml
  become: yes
  tasks:
    - name: Read device information (always use unit when probing)
      parted: device=/dev/mmcblk0 unit=s
      register: mmcblk0_info

    - debug:
        var: mmcblk0_info.partitions[2].begin
        verbosity: 0

    - name: Replace 3rd partition
      shell: |
        fdisk /dev/mmcblk0 <<EOF
        d
        3
        n
        p
        3
        {{ mmcblk0_info.partitions[2].begin | string | splitext | max }}
        
        p
        w
        EOF
      register: mmcblk0_out

    - debug:
        var: mmcblk0_out
        verbosity: 0

    - name: Extend the FS
      filesystem:
        fstype: 'ext4'
        dev: '/dev/mmcblk0p3'
        resizefs: yes

    - name: Update GPU memory configuration block in /boot/efi/config.txt
      blockinfile:
        path: /boot/efi/config.txt
        insertafter: "gpu_mem=32"
        block: |
          #gpu_mem_256=112
          #gpu_mem_512=368
          #gpu_mem_1024=448
          cma_lwm=16
          cma_hwm=32
          cma_offline_start=16

    - name: Test if dynamic GPU memory allocation is activated
      command: grep "coherent_pool=6M smsc95xx.turbo_mode=N" /boot/grub/grub.conf
      register: dynamic_gpu
      ignore_errors: True

    - debug:
        var: dynamic_gpu

    - name: Ensure dynamic GPU memory allocation is activated
      lineinfile:
        path: /boot/grub/grub.conf
        regexp: '^( *)kernel (.*)$'
        line: '\1kernel \2 coherent_pool=6M smsc95xx.turbo_mode=N'
        backrefs: yes
        firstmatch: yes
      when: dynamic_gpu is failed

    - name: Install RPMfusion repositories
      shell: rpm -q rpmfusion-nonfree-release || dnf -y install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

    - name: Remove packages
      package:
        name:
          - sylpheed
        state: absent

    - name: Install packages
      package:
        name:
          - vim
          - screen
            #- chromium-freeworld
          - firefox
          - claws-mail
          - claws-mail-plugins-pdf-viewer
          - libreoffice
          - cheese
          - kamoso
          - fswebcam
          - camorama
          - guvcview
          - xpdf
          - qpdfview
          - cups-pdf
        state: present

